apiVersion: v1
kind: Service
metadata:
  name:  postgresService
spec:
  selector:
    name: postgres-pod
    app: demo-voting-app
  type:  ClusterIP
  ports:
  - name:  postgresPort
    port:  5432
    targetPort:  5432
    