apiVersion: v1
kind: app
metadata:
  name: postgres-pod
  labels:
    name: postgres-pod
    app: demo-voting-app
spec:
  containers:
    - image:  postgres:9.4
      name:  postgres
      ports:
      - port:  5432



  