apiVersion: v1
kind: app
metadata:
  name: redis-pod
  labels:
    name: redis
    app: demo-voting-app
spec:
  containers:
    - image:  redis
      name:  redis
      ports:
      - port:  6379
     

  