apiVersion: v1
kind: Service
metadata:
  name:  redisService
spec:
  selector:
    name: redis
    app: demo-voting-app
  type:  ClusterIP
  ports:
  - name:  redisServicePort
    port:  6379
    targetPort:  6379