apiVersion: v1
kind: Service
metadata:
  name:  resultappservice
spec:
  selector:
    name: result-app-pod
    app: demo-voting-app
  type:  LoadBalancer
  ports:
  - name:  resultappport
    port:  80
    targetPort:  80